### ISSUE TITLE
Error "type 'int' is not a subtype of type 'double'" when api conversion result is int

### ISSUE THREAD

**Issue by dmitry-kotorov** [emreesen27/Flutter_Currencies_Tracker#1]
When backend returns int conversation result, it fails to create ConversionModel

type 'int' is not a subtype of type 'double', #0      Currency.getConversion (package:flutter_currencies_tracker/currency.dart:25:34)

**Comment by emreesen27** [comment]
hi, i haven't come across such a return type but you might be right.

* Upgrade to version 0.0.4

* Change usage in this way.
```dart
    var response = await Currency.getConversion(from: "USD", to: "TRY", amount: "1");
    var rate = response.rate; ```

**Comment by dmitry-kotorov** [comment]
Thank you!
